"""empty message

Revision ID: 55acf66bc567
Revises: None
Create Date: 2015-08-04 18:40:50.297103

"""

# revision identifiers, used by Alembic.
revision = '55acf66bc567'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experimental_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_fk', sa.Integer(), nullable=True),
    sa.Column('diff_exp_method', sa.String(length=255), nullable=True),
    sa.Column('ttest_correction_method', sa.String(length=255), nullable=True),
    sa.Column('ttest_threshold', sa.Float(), nullable=True),
    sa.Column('chdir_cutoff', sa.Integer(), nullable=True),
    sa.Column('organism', sa.String(length=255), nullable=True),
    sa.Column('cell', sa.String(length=255), nullable=True),
    sa.Column('perturbation', sa.String(length=255), nullable=True),
    sa.Column('gene', sa.String(length=255), nullable=True),
    sa.Column('disease', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=255), nullable=True),
    sa.Column('normalize', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_fk'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diff_exp_method')
    op.drop_table('ttest_correction_method')
    op.drop_constraint(u'extractions_ibfk_1', 'extractions', type_='foreignkey')
    op.drop_constraint(u'extractions_ibfk_2', 'extractions', type_='foreignkey')
    op.drop_column('extractions', 'cutoff')
    op.drop_column('extractions', 'perturbation')
    op.drop_column('extractions', 'diff_exp_method_fk')
    op.drop_column('extractions', 'ttest_correction_method_fk')
    op.drop_column('extractions', 'disease')
    op.drop_column('extractions', 'cell')
    op.drop_column('extractions', 'threshold')
    op.drop_column('extractions', 'gene')
    op.drop_column('extractions', 'organism')
    op.drop_column('rankedgenes', 'value_type')
    op.drop_index('extraction_id', table_name='softfiles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('extraction_id', 'softfiles', ['extraction_fk'], unique=False)
    op.add_column('rankedgenes', sa.Column('value_type', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('extractions', sa.Column('organism', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('extractions', sa.Column('gene', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('extractions', sa.Column('threshold', mysql.FLOAT(), nullable=True))
    op.add_column('extractions', sa.Column('cell', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('extractions', sa.Column('disease', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('extractions', sa.Column('ttest_correction_method_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('extractions', sa.Column('diff_exp_method_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('extractions', sa.Column('perturbation', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('extractions', sa.Column('cutoff', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'extractions_ibfk_2', 'extractions', 'ttest_correction_method', ['ttest_correction_method_fk'], ['id'])
    op.create_foreign_key(u'extractions_ibfk_1', 'extractions', 'diff_exp_method', ['diff_exp_method_fk'], ['id'])
    op.create_table('ttest_correction_method',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('diff_exp_method',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('experimental_metadata')
    ### end Alembic commands ###
